{{-- <script src="{{ asset('system/assets/plugins/jquery/jquery-3.1.0.min.js')}}"></script> --}}
        <script src="{{ asset('system/assets/plugins/bootstrap/js/bootstrap.min.js')}}"></script>
        <script src="{{ asset('system/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
        <script src="{{ asset('system/assets/plugins/uniform/js/jquery.uniform.standalone.js')}}"></script>
        <script src="{{ asset('system/assets/plugins/switchery/switchery.min.js')}}"></script>
        <script src="{{ asset('system/assets/plugins/d3/d3.min.js')}}"></script>
        <script src="{{ asset('system/assets/plugins/nvd3/nv.d3.min.js')}}"></script>
        <script src="{{ asset('system/assets/plugins/flot/jquery.flot.min.js')}}"></script>
        <script src="{{ asset('system/assets/plugins/flot/jquery.flot.time.min.js')}}"></script>
        <script src="{{ asset('system/assets/plugins/flot/jquery.flot.symbol.min.js')}}"></script>
        <script src="{{ asset('system/assets/plugins/flot/jquery.flot.resize.min.js')}}"></script>
        <script src="{{ asset('system/assets/plugins/flot/jquery.flot.tooltip.min.js')}}"></script>
        <script src="{{ asset('system/assets/plugins/flot/jquery.flot.pie.min.js')}}"></script>
        <script src="{{ asset('system/assets/plugins/chartjs/chart.min.js')}}"></script>
        <script src="{{ asset('system/assets/js/ecaps.min.js')}}"></script>
        <script src="{{ asset('system/assets/js/pages/dashboard.j')}}s"></script>
